default: &default
  adapter: postgresql
  encoding: utf8
  database: chlar4_web
  pool: 25
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: sur_dev

test:
  <<: *default
  database: sur_test

production:
  <<: *default
  database: sur_prod
  username: postgres
  password: postgres
  host: localhost